language: python
python:
#  - "2.6" doesn't discover
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
# command to run tests
script: python -m unittest discover -s tests
